import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import githubLogo from "../assets/github.png";
import Link from "next/link";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {
  const [loggedIn, setLoggedIn] = useState(false);
  const [user, setUser] = useState(null);

  useEffect(async () => {
    const token = new URLSearchParams(window.location.search).get(
      "access_token"
    );
    try {
      const response = await axios.get("http://localhost:8010/proxy/user", {
        headers: {
          Authorization: "token " + token,
        },
      });

      setUser(response.data);
      setLoggedIn(true);
    } catch (error) {
      console.log(error);
    }
  }, []);

  const loginUrl =
    "https://github.com/login/oauth/authorize?client_id=e9224fe2241a5e53138e&redirect_uri=http://localhost:8010/oauth/redirect";
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainContent}>
        <div className={styles.card}>
          <Image src={githubLogo} width={70} height={70} />
          <div className={styles.textContent}>
            <h2>Welcome to developer community</h2>
            <p>Please Login to continue to our service</p>
            <button className={styles.primaryButton}>
              <Link href={loginUrl}>Log In</Link>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
